### ISSUE TITLE
PT distributed training: RuntimeError: Socket Timeout in eval

### ISSUE THREAD

**Issue by albertz** [rwth-i6/returnn#1621]
The main rank (0) evaluates the dev dataset and runs fine. In my case, it's quite slow.

The other ranks after a while fail with this timeout error:
```
...
RETURNN starting up, version 1.20240908.014935+git.7390bea6, date/time 2024-09-08-21-02-13 (UTC+0000), pid 748658, cwd /work/asr4/zeyer/setups-data/combined/2021-05-31/work/i6_core/returnn/training/ReturnnTrainingJob.3WJVAQl19A2n/work, Python /work/tools/users/zeyer/py-envs/py3.11-torch2.1/bin/python3.11
RETURNN command line options: ['/u/zeyer/setups/combined/2021-05-31/work/i6_core/returnn/training/ReturnnTrainingJob.3WJVAQl19A2n/output/returnn.config']
Hostname: cn-232
Installed native_signal_handler.so.Installed native_signal_handler.so.

Installed native_signal_handler.so.
PyTorch: 2.1.0+cu121 (7bcf7da3a268b435777fe87c7794c382f444e86d) (<site-package> in /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch)
PyTorch: 2.1.0+cu121 (7bcf7da3a268b435777fe87c7794c382f444e86d) (<site-package> in /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch)
PyTorch: 2.1.0+cu121 (7bcf7da3a268b435777fe87c7794c382f444e86d) (<site-package> in /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch)
Torch: Hostname cn-232, pid 748658, using GPU 2.
Torch: Hostname cn-232, pid 748656, using GPU 0.
Torch: Hostname cn-232, pid 748657, using GPU 1.
...
Last epoch model not yet evaluated on dev. Doing that now.
Memory usage (cuda:3): alloc cur 1.3GB alloc peak 1.3GB reserved cur 1.3GB reserved peak 1.3GB
Last epoch model not yet evaluated on dev. Doing that now.
Memory usage (cuda:0): alloc cur 1.3GB alloc peak 1.3GB reserved cur 1.3GB reserved peak 1.3GB
Evaluating dataset 'dev'
Last epoch model not yet evaluated on dev. Doing that now.
Memory usage (cuda:1): alloc cur 1.3GB alloc peak 1.3GB reserved cur 1.3GB reserved peak 1.3GB
Last epoch model not yet evaluated on dev. Doing that now.
Memory usage (cuda:2): alloc cur 1.3GB alloc peak 1.3GB reserved cur 1.3GB reserved peak 1.3GB
...
ep 1 dev eval, step 343, min_wer 0.083, ce 0.559, fer 0.942, mem_usage:cuda:0 1.6GB
ep 1 dev eval, step 344, min_wer -0.111, ce 0.696, fer 0.951, mem_usage:cuda:0 1.6GB
ep 1 dev eval, step 345, min_wer -0.222, ce 0.876, fer 0.942, mem_usage:cuda:0 1.6GB
ep 1 dev eval, step 346, min_wer 0.083, ce 0.615, fer 0.944, mem_usage:cuda:0 1.6GB
ep 1 dev eval, step 347, min_wer -0.139, ce 0.622, fer 0.938, mem_usage:cuda:0 1.6GB
ep 1 dev eval, step 348, min_wer 0.006, ce 0.712, fer 0.937, mem_usage:cuda:0 1.6GB
MEMORY: sub proc TDL worker 0(750472) increased RSS: rss=436.4MB pss=286.5MB uss=270.5MB shared=165.9MB
MEMORY: total (main 748656, 2024-09-08, 21:33:35, 21 procs): pss=5.8GB uss=5.0GB
ep 1 dev eval, step 349, min_wer -0.014, ce 0.537, fer 0.938, mem_usage:cuda:0 1.6GB
ep 1 dev eval, step 350, min_wer -0.160, ce 0.730, fer 0.930, mem_usage:cuda:0 1.6GB
Unhandled exception <class 'RuntimeError'> in thread <_MainThread(MainThread, started 139851100856320)>, proc 748657.

Thread <Thread(QueueFeederThread, started daemon 139844755904064)>:
Unhandled exception <class 'RuntimeError'> in thread <_MainThread(MainThread, started 140642136944640)>, proc 748658.

Thread <Thread(QueueFeederThread, started daemon 140636498601536)>:
Unhandled exception <class 'RuntimeError'> in thread <_MainThread(MainThread, started 140698407014400)>, proc 748659.

Thread <Thread(QueueFeederThread, started daemon 140692089206336)>:
...
EXCEPTION
Traceback (most recent call last):
  File "/u/zeyer/setups/combined/2021-05-31/tools/returnn/rnn.py", line 11, in <module>
    line: main()
    locals:
      main = <local> <function main at 0x7fe9a210cea0>
  File "/u/zeyer/setups/combined/2021-05-31/tools/returnn/returnn/__main__.py", line 737, in main
    line: execute_main_task()
    locals:
      execute_main_task = <global> <function execute_main_task at 0x7fe9a210cd60>
  File "/u/zeyer/setups/combined/2021-05-31/tools/returnn/returnn/__main__.py", line 543, in execute_main_task
    line: engine.train()
    locals:
      engine = <global> <returnn.torch.engine.Engine object at 0x7fe8b7262490>
      engine.train = <global> <bound method Engine.train of <returnn.torch.engine.Engine object at 0x7fe8b7262490>>
  File "/u/zeyer/setups/combined/2021-05-31/tools/returnn/returnn/torch/engine.py", line 226, in Engine.train
    line: self._check_missing_eval()
    locals:
      self = <local> <returnn.torch.engine.Engine object at 0x7fe8b7262490>
      self._check_missing_eval = <local> <bound method Engine._check_missing_eval of <returnn.torch.engine.Engine object at 0x7fe8b7262490>>
  File "/u/zeyer/setups/combined/2021-05-31/tools/returnn/returnn/torch/engine.py", line 1186, in Engine._check_missing_eval
    line: self.eval_model(skip_already_evaluated=True)
    locals:
      self = <local> <returnn.torch.engine.Engine object at 0x7fe8b7262490>
      self.eval_model = <local> <bound method Engine.eval_model of <returnn.torch.engine.Engine object at 0x7fe8b7262490>>
      skip_already_evaluated = <not found>
  File "/u/zeyer/setups/combined/2021-05-31/tools/returnn/returnn/torch/engine.py", line 523, in Engine.eval_model
    line: iter(data_loader)
    locals:
      iter = <builtin> <built-in function iter>
      data_loader = <local> <torch.utils.data.dataloader.DataLoader object at 0x7fe8b40a1f50>
  File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 433, in DataLoader.__iter__
    line: self._iterator = self._get_iterator()
    locals:
      self = <local> <torch.utils.data.dataloader.DataLoader object at 0x7fe8b40a1f50>
      self._iterator = <local> None
      self._get_iterator = <local> <bound method DataLoader._get_iterator of <torch.utils.data.dataloader.DataLoader object at 0x7fe8b40a1f50>>
  File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 386, in DataLoader._get_iterator
    line: return _MultiProcessingDataLoaderIter(self)
    locals:
      _MultiProcessingDataLoaderIter = <global> <class 'torch.utils.data.dataloader._MultiProcessingDataLoaderIter'>
      self = <local> <torch.utils.data.dataloader.DataLoader object at 0x7fe8b40a1f50>
  File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 991, in _MultiProcessingDataLoaderIter.__init__
    line: super().__init__(loader)
    locals:
      super = <builtin> <class 'super'>
      __init__ = <not found>
      loader = <local> <torch.utils.data.dataloader.DataLoader object at 0x7fe8b40a1f50>
  File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 570, in _BaseDataLoaderIter.__init__
    line: self._pg = dist.new_group(backend="gloo")
    locals:
      self = <local> <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7fe87e404150>
      self._pg = <local> None
      dist = <global> <module 'torch.distributed' from '/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/distributed/__init__.py'>
      dist.new_group = <global> <function new_group at 0x7fe99f1a7420>
      backend = <not found>
  File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 74, in _store_based_barrier
    line: func_return = func(*args, **kwargs)
    locals:
      func_return = <not found>
      func = <local> <function new_group at 0x7fe99f1a7380>
      args = <local> ()
      kwargs = <local> {'backend': 'gloo'}
  File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 3881, in new_group
    line: return _new_group_with_tag(ranks, timeout, backend, pg_options, None, use_local_synchronization=use_local_synchronization)
    locals:
      _new_group_with_tag = <global> <function _new_group_with_tag at 0x7fe99f1a74c0>
      ranks = <local> None
      timeout = <local> datetime.timedelta(seconds=1800)
      backend = <local> 'gloo'
      pg_options = <local> None
      use_local_synchronization = <local> False
  File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 3944, in _new_group_with_tag
    line: pg, pg_store = _new_process_group_helper(
              group_world_size,
              group_rank,
              ranks,
              backend,
              default_store,
              group_name=group_name,
              pg_options=pg_options,
              timeout=timeout,
              pg_tag=pg_tag
          )
    locals:
      pg = <not found>
      pg_store = <not found>
      _new_process_group_helper = <global> <function _new_process_group_helper at 0x7fe99f1a4540>
      group_world_size = <local> 4
      group_rank = <local> 2
      ranks = <local> [0, 1, 2, 3]
      backend = <local> 'gloo'
      default_store = <local> <torch.distributed.distributed_c10d.PrefixStore object at 0x7fe9a091b1b0>
      group_name = <local> '2'
      pg_options = <local> None
      timeout = <local> datetime.timedelta(seconds=1800)
      pg_tag = <local> None
  File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 1264, in _new_process_group_helper
    line: backend_class = ProcessGroupGloo(backend_prefix_store, group_rank, group_size, timeout=timeout)
    locals:
      backend_class = <not found>
      ProcessGroupGloo = <global> <class 'torch.distributed.distributed_c10d.ProcessGroupGloo'>
      backend_prefix_store = <local> <torch.distributed.distributed_c10d.PrefixStore object at 0x7fe87e413470>
      group_rank = <local> 2
      group_size = <local> 4
      timeout = <local> datetime.timedelta(seconds=1800)
RuntimeError: Socket Timeout
```
(Note, the `_check_missing_eval` is not really the problem. It crashed already in the first run where it did the eval right after train. Now every new run goes into `_check_missing_eval`, and then fails there.)

As you see from the exception, there is a `timeout = <local> datetime.timedelta(seconds=1800)`. I did not measure the time exactly, but I think that is more or less exactly when it breaks. That are 30 minutes. I assume in most other cases, the eval dataset is iterated much faster than that. So that could explain why it occurs now and otherwise not.

But I don't fully understand it. It would imply that rank 0 syncs this process group only at the end of the dataset iteration, such that it is fine in most cases (eval less than 30 mins) but now it is not. Specifically, I don't understand what it would do at the end of the dataset iteration in rank 0. The `DataLoader` iterator (`_MultiProcessingDataLoaderIter`) should be persistent (we set `persistent_workers=True`), i.e. the iterator will not be deleted at the end, i.e. the process group should stay alive afterwards. Also, the only use of this process group seems to be to `_share_dist_seed`. But looking at the stacktrace of the exception, it doesn't even get there, it still hangs in the process group creation.

The sync / the timeout happens here in the creation of `ProcessGroupGloo`. The rank 0 should also have done the same, right at the beginning, not at the end. Maybe sth is missing to perform the communication, which then happens only after the dataset iteration?

**Comment by albertz** [comment]
Hm, so usually we do have some frequent communication over Gloo, e.g. via this (that's a tensor on CPU):
```python
_has_data = torch.tensor([extern_data_raw is not None], dtype=torch.int8)
if self._torch_distributed_ctx:
    # use all reduce to check if all workers have data, if at least one worker does not have data,
    # all workers finish this epoch
    torch.distributed.all_reduce(_has_data, op=torch.distributed.ReduceOp.MIN)
```
So maybe, in general, if no communication happens over Gloo for more than 30 mins, it results in such an exception?

But why does it hang in the process group creation? That still doesn't make sense to me.

Also, I thought there is such rendezvous logic anyway already which performs such checks. It doesn't make sense to me that I should take care of this. Also, this `_has_data` sync logic is quite custom for us. I assume in other implementations, it's not so uncommon that you mostly use NCCL and Gloo stays inactive for more than 30 minutes.

**Comment by albertz** [comment]
With more debug info:
```python
# https://pytorch.org/docs/stable/distributed.html#torch-distributed-debug
job.set_env("TORCH_CPP_LOG_LEVEL", "INFO")
job.set_env("TORCH_DISTRIBUTED_DEBUG", "DETAIL")
job.set_env("TORCH_SHOW_CPP_STACKTRACES", "1")
```
I get:
```
...
Uname: uname_result(system='Linux', node='cn-232', release='5.15.0-39-generic', version='#42-Ubuntu SMP Thu Jun 9 23:42:32 UTC 2022', machine='x86_64')
Load: (1.173828125, 1.7880859375, 2.19140625)
[2024-09-09 16:43:00,116] INFO: ------------------------------------------------------------
[2024-09-09 16:43:00,116] INFO: Starting subtask for arg id: 0 args: []
[2024-09-09 16:43:00,116] INFO: ------------------------------------------------------------
[I debug.cpp:49] [c10d] The debug level is set to DETAIL.
[2024-09-09 16:43:05,022] INFO: Run time: 0:00:05 CPU: 0.40% RSS: 407MB VMS: 3.63GB
master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
[I socket.cpp:452] [c10d - debug] The server socket will attempt to listen on an IPv6 address.
[I socket.cpp:502] [c10d - debug] The server socket is attempting to listen on [::]:0.
[I socket.cpp:576] [c10d] The server socket has started to listen on [::]:0.
[I TCPStore.cpp:252] [c10d - debug] The server has started on port = 43339.
[I socket.cpp:686] [c10d - debug] The client socket will attempt to connect to an IPv6 address of (localhost, 43339).
[I socket.cpp:761] [c10d - trace] The client socket is attempting to connect to [localhost.localdomain]:43339.
[I socket.cpp:849] [c10d] The client socket has connected to [localhost.localdomain]:43339 on [localhost.localdomain]:56554.
[I TCPStore.cpp:261] [c10d - debug] TCP client connected to host localhost:43339
[I socket.cpp:297] [c10d - debug] The server socket on [::]:43339 has accepted a connection from [localhost.localdomain]:56554.
WARNING:root:Settings file 'settings.py' does not exist, ignoring it ([Errno 2] No such file or directory: 'settings.py').
WARNING:root:Settings file 'settings.py' does not exist, ignoring it ([Errno 2] No such file or directory: 'settings.py').
WARNING:root:Settings file 'settings.py' does not exist, ignoring it ([Errno 2] No such file or directory: 'settings.py').
WARNING:root:Settings file 'settings.py' does not exist, ignoring it ([Errno 2] No such file or directory: 'settings.py').
[I debug.cpp:49] [c10d] The debug level is set to DETAIL.
[I debug.cpp:49] [c10d] The debug level is set to DETAIL.
[I debug.cpp:49] [c10d] The debug level is set to DETAIL.
[I debug.cpp:49] [c10d] The debug level is set to DETAIL.
[2024-09-09 16:43:10,043] INFO: Run time: 0:00:10 CPU: 0.40% RSS: 1.94GB VMS: 17.70GB
[I socket.cpp:686] [c10d - debug] The client socket will attempt to connect to an IPv6 address of (cn-232.informatik.rwth-aachen.de, 35473).
[I socket.cpp:686] [c10d - debug] The client socket will attempt to connect to an IPv6 address of (cn-232.informatik.rwth-aachen.de, 35473).
[I socket.cpp:761] [c10d - trace] The client socket is attempting to connect to [cn-232.informatik.rwth-aachen.de]:35473.
[I socket.cpp:761] [c10d - trace] The client socket is attempting to connect to [cn-232.informatik.rwth-aachen.de]:35473.
[I socket.cpp:830] [c10d - trace] The server socket on [cn-232.informatik.rwth-aachen.de]:35473 is not yet listening (errno: 111 - Connection refused), will retry.
[I socket.cpp:830] [c10d - trace] The server socket on [cn-232.informatik.rwth-aachen.de]:35473 is not yet listening (errno: 111 - Connection refused), will retry.
[I socket.cpp:686] [c10d - debug] The client socket will attempt to connect to an IPv6 address of (cn-232.informatik.rwth-aachen.de, 35473).
[I socket.cpp:761] [c10d - trace] The client socket is attempting to connect to [cn-232.informatik.rwth-aachen.de]:35473.
[I socket.cpp:830] [c10d - trace] The server socket on [cn-232.informatik.rwth-aachen.de]:35473 is not yet listening (errno: 111 - Connection refused), will retry.
[I socket.cpp:452] [c10d - debug] The server socket will attempt to listen on an IPv6 address.
[I socket.cpp:502] [c10d - debug] The server socket is attempting to listen on [::]:35473.
[I socket.cpp:576] [c10d] The server socket has started to listen on [::]:35473.
[I TCPStore.cpp:252] [c10d - debug] The server has started on port = 35473.
[I socket.cpp:686] [c10d - debug] The client socket will attempt to connect to an IPv6 address of (cn-232.informatik.rwth-aachen.de, 35473).
[I socket.cpp:761] [c10d - trace] The client socket is attempting to connect to [cn-232.informatik.rwth-aachen.de]:35473.
[I socket.cpp:849] [c10d] The client socket has connected to [cn-232.informatik.rwth-aachen.de]:35473 on [cn-232.informatik.rwth-aachen.de]:46194.
[I TCPStore.cpp:261] [c10d - debug] TCP client connected to host cn-232.informatik.rwth-aachen.de:35473
[I socket.cpp:297] [c10d - debug] The server socket on [::]:35473 has accepted a connection from [cn-232.informatik.rwth-aachen.de]:46194.
[I socket.cpp:761] [c10d - trace] The client socket is attempting to connect to [cn-232.informatik.rwth-aachen.de]:35473.
[I socket.cpp:761] [c10d - trace] The client socket is attempting to connect to [cn-232.informatik.rwth-aachen.de]:35473.
[I socket.cpp:297] [c10d - debug] The server socket on [::]:35473 has accepted a connection from [cn-232.informatik.rwth-aachen.de]:46196.
[I socket.cpp:849] [c10d] The client socket has connected to [cn-232.informatik.rwth-aachen.de]:35473 on [cn-232.informatik.rwth-aachen.de]:46198.
[I TCPStore.cpp:261] [c10d - debug] TCP client connected to host cn-232.informatik.rwth-aachen.de:35473
[I socket.cpp:849] [c10d] The client socket has connected to [cn-232.informatik.rwth-aachen.de]:35473 on [cn-232.informatik.rwth-aachen.de]:46196.
[I TCPStore.cpp:261] [c10d - debug] TCP client connected to host cn-232.informatik.rwth-aachen.de:35473
[I socket.cpp:297] [c10d - debug] The server socket on [::]:35473 has accepted a connection from [cn-232.informatik.rwth-aachen.de]:46198.
[I socket.cpp:761] [c10d - trace] The client socket is attempting to connect to [cn-232.informatik.rwth-aachen.de]:35473.
[I socket.cpp:297] [c10d - debug] The server socket on [::]:35473 has accepted a connection from [cn-232.informatik.rwth-aachen.de]:46200.
[I socket.cpp:849] [c10d] The client socket has connected to [cn-232.informatik.rwth-aachen.de]:35473 on [cn-232.informatik.rwth-aachen.de]:46200.
[I TCPStore.cpp:261] [c10d - debug] TCP client connected to host cn-232.informatik.rwth-aachen.de:35473
[I ProcessGroupNCCL.cpp:686] [Rank 0] ProcessGroupNCCL initialization options:NCCL_ASYNC_ERROR_HANDLING: 1, NCCL_DESYNC_DEBUG: 1, NCCL_ENABLE_TIMING: 1, NCCL_BLOCKING_WAIT: 0, TIMEOUT(ms): 1800000, USE_HIGH_PRIORITY_STREAM: 0, TORCH_DISTRIBUTED_DEBUG: DETAIL, NCCL_DEBUG: OFF, ID=102123600
[I ProcessGroupNCCL.cpp:686] [Rank 3] ProcessGroupNCCL initialization options:NCCL_ASYNC_ERROR_HANDLING: 1, NCCL_DESYNC_DEBUG: 1, NCCL_ENABLE_TIMING: 1, NCCL_BLOCKING_WAIT: 0, TIMEOUT(ms): 1800000, USE_HIGH_PRIORITY_STREAM: 0, TORCH_DISTRIBUTED_DEBUG: DETAIL, NCCL_DEBUG: OFF, ID=125099088
[I ProcessGroupNCCL.cpp:686] [Rank 1] ProcessGroupNCCL initialization options:NCCL_ASYNC_ERROR_HANDLING: 1, NCCL_DESYNC_DEBUG: 1, NCCL_ENABLE_TIMING: 1, NCCL_BLOCKING_WAIT: 0, TIMEOUT(ms): 1800000, USE_HIGH_PRIORITY_STREAM: 0, TORCH_DISTRIBUTED_DEBUG: DETAIL, NCCL_DEBUG: OFF, ID=132157168
[I ProcessGroupNCCL.cpp:686] [Rank 2] ProcessGroupNCCL initialization options:NCCL_ASYNC_ERROR_HANDLING: 1, NCCL_DESYNC_DEBUG: 1, NCCL_ENABLE_TIMING: 1, NCCL_BLOCKING_WAIT: 0, TIMEOUT(ms): 1800000, USE_HIGH_PRIORITY_STREAM: 0, TORCH_DISTRIBUTED_DEBUG: DETAIL, NCCL_DEBUG: OFF, ID=124615568
RETURNN starting up, version 1.20240908.014935+git.7390bea6, date/time 2024-09-09-16-43-14 (UTC+0000), pid 785299, cwd /work/asr4/zeyer/setups-data/combined/2021-05-31/work/i6_core/returnn/training/ReturnnTrainingJob.3WJVAQl19A2n/work, Python /work/tools/users/zeyer/py-envs/py3.11-torch2.1/bin/python3.11
RETURNN command line options: ['/u/zeyer/setups/combined/2021-05-31/work/i6_core/returnn/training/ReturnnTrainingJob.3WJVAQl19A2n/output/returnn.config']
Hostname: cn-232
...
Load optimizer /u/zeyer/setups/combined/2021-05-31/work/i6_core/returnn/training/ReturnnTrainingJob.3WJVAQl19A2n/output/models/epoch.001.opt.pt
MEMORY: main proc python3.11(785300) increased RSS: rss=3.5GB pss=2.8GB uss=2.4GB shared=1.0GB
MEMORY: main proc python3.11(785298) increased RSS: rss=3.5GB pss=2.9GB uss=2.4GB shared=1.0GB
MEMORY: total (main 785300, 2024-09-09, 16:44:33, 16 procs): pss=4.6GB uss=3.8GB
MEMORY: main proc python3.11(785301) increased RSS: rss=3.4GB pss=2.8GB uss=2.4GB shared=1.0GB
MEMORY: sub proc watch memory(785464) increased RSS: rss=50.2MB pss=28.8MB uss=28.5MB shared=21.6MB
MEMORY: total (main 785298, 2024-09-09, 16:44:33, 16 procs): pss=4.7GB uss=3.9GB
MEMORY: total (main 785301, 2024-09-09, 16:44:33, 16 procs): pss=4.6GB uss=3.8GB
MEMORY: total (main 785299, 2024-09-09, 16:44:33, 16 procs): pss=4.7GB uss=3.9GB
[2024-09-09 16:44:35,736] INFO: Run time: 0:01:35 CPU: 0.80% RSS: 21.35GB VMS: 628.17GB
Last epoch model not yet evaluated on dev. Doing that now.
Last epoch model not yet evaluated on dev. Doing that now.
Memory usage (cuda:0): alloc cur 1.3GB alloc peak 1.3GB reserved cur 1.3GB reserved peak 1.3GB
Evaluating dataset 'dev'
Memory usage (cuda:3): alloc cur 1.3GB alloc peak 1.3GB reserved cur 1.3GB reserved peak 1.3GB
Last epoch model not yet evaluated on dev. Doing that now.
Last epoch model not yet evaluated on dev. Doing that now.
Memory usage (cuda:1): alloc cur 1.3GB alloc peak 1.3GB reserved cur 1.3GB reserved peak 1.3GB
Memory usage (cuda:2): alloc cur 1.3GB alloc peak 1.3GB reserved cur 1.3GB reserved peak 1.3GB
[I ProcessGroupWrapper.cpp:562] [Rank 0] Running collective: CollectiveFingerPrint(SequenceNumber=0, OpType=BROADCAST, TensorShape=[], TensorDtypes=Long, TensorDeviceTypes=TensorOptions(dtype=float (default), device=cpu, layout=Strided (default), requires_grad=false (default), pinned_memory=false (default), memory_format=(nullopt)))
[I ProcessGroupWrapper.cpp:562] [Rank 1] Running collective: CollectiveFingerPrint(SequenceNumber=0, OpType=BROADCAST, TensorShape=[], TensorDtypes=Long, TensorDeviceTypes=TensorOptions(dtype=float (default), device=cpu, layout=Strided (default), requires_grad=false (default), pinned_memory=false (default), memory_format=(nullopt)))
[I ProcessGroupWrapper.cpp:562] [Rank 3] Running collective: CollectiveFingerPrint(SequenceNumber=0, OpType=BROADCAST, TensorShape=[], TensorDtypes=Long, TensorDeviceTypes=TensorOptions(dtype=float (default), device=cpu, layout=Strided (default), requires_grad=false (default), pinned_memory=false (default), memory_format=(nullopt)))
[I ProcessGroupWrapper.cpp:562] [Rank 2] Running collective: CollectiveFingerPrint(SequenceNumber=0, OpType=BROADCAST, TensorShape=[], TensorDtypes=Long, TensorDeviceTypes=TensorOptions(dtype=float (default), device=cpu, layout=Strided (default), requires_grad=false (default), pinned_memory=false (default), memory_format=(nullopt)))
[I ProcessGroupWrapper.cpp:562] [Rank 3] Running collective: CollectiveFingerPrint(SequenceNumber=1, OpType=BROADCAST, TensorShape=[], TensorDtypes=Long, TensorDeviceTypes=TensorOptions(dtype=float (default), device=cpu, layout=Strided (default), requires_grad=false (default), pinned_memory=false (default), memory_format=(nullopt)))
[I ProcessGroupWrapper.cpp:562] [Rank 1] Running collective: CollectiveFingerPrint(SequenceNumber=1, OpType=BROADCAST, TensorShape=[], TensorDtypes=Long, TensorDeviceTypes=TensorOptions(dtype=float (default), device=cpu, layout=Strided (default), requires_grad=false (default), pinned_memory=false (default), memory_format=(nullopt)))
[I ProcessGroupWrapper.cpp:562] [Rank 2] Running collective: CollectiveFingerPrint(SequenceNumber=1, OpType=BROADCAST, TensorShape=[], TensorDtypes=Long, TensorDeviceTypes=TensorOptions(dtype=float (default), device=cpu, layout=Strided (default), requires_grad=false (default), pinned_memory=false (default), memory_format=(nullopt)))
[I ProcessGroupWrapper.cpp:562] [Rank 0] Running collective: CollectiveFingerPrint(SequenceNumber=1, OpType=BROADCAST, TensorShape=[], TensorDtypes=Long, TensorDeviceTypes=TensorOptions(dtype=float (default), device=cpu, layout=Strided (default), requires_grad=false (default), pinned_memory=false (default), memory_format=(nullopt)))
WARNING:root:Settings file 'settings.py' does not exist, ignoring it ([Errno 2] No such file or directory: 'settings.py').
WARNING:root:Settings file 'settings.py' does not exist, ignoring it ([Errno 2] No such file or directory: 'settings.py').
WARNING:root:Settings file 'settings.py' does not exist, ignoring it ([Errno 2] No such file or directory: 'settings.py').
WARNING:root:Settings file 'settings.py' does not exist, ignoring it ([Errno 2] No such file or directory: 'settings.py').
MEMORY: sub proc python3.11(787159) initial: rss=66.0MB pss=40.7MB uss=40.3MB shared=25.7MB
MEMORY: total (main 785300, 2024-09-09, 16:44:38, 17 procs): pss=4.7GB uss=3.9GB
...
MEMORY: sub proc python3.11(787163) initial: rss=207.8MB pss=118.3MB uss=110.0MB shared=97.8MB
MEMORY: total (main 785299, 2024-09-09, 16:44:39, 17 procs): pss=4.8GB uss=4.0GB
[I debug.cpp:49] [c10d] The debug level is set to DETAIL.
[I debug.cpp:49] [c10d] The debug level is set to DETAIL.
[I debug.cpp:49] [c10d] The debug level is set to DETAIL.
[I debug.cpp:49] [c10d] The debug level is set to DETAIL.
WARNING:root:Settings file 'settings.py' does not exist, ignoring it ([Errno 2] No such file or directory: 'settings.py').
WARNING:root:Settings file 'settings.py' does not exist, ignoring it ([Errno 2] No such file or directory: 'settings.py').
...
ep 1 dev eval, step 0, min_wer -0.125, ce 0.980, fer 0.968, mem_usage:cuda:0 1.4GB
MEMORY: sub proc MPD worker 1(787510) increased RSS: rss=112.9MB pss=85.6MB uss=85.3MB shared=27.6MB
MEMORY: sub proc MPD worker 2(787617) increased RSS: rss=113.2MB pss=85.7MB uss=85.4MB shared=27.7MB
MEMORY: total (main 785298, 2024-09-09, 16:45:01, 21 procs): pss=5.8GB uss=5.0GB
ep 1 dev eval, step 1, min_wer -2.375, ce 0.816, fer 0.978, mem_usage:cuda:0 1.4GB
ep 1 dev eval, step 2, min_wer -0.436, ce 0.518, fer 0.966, mem_usage:cuda:0 1.4GB
MEMORY: sub proc MPD worker 3(787726) increased RSS: rss=113.9MB pss=86.7MB uss=86.4MB shared=27.6MB
MEMORY: total (main 785298, 2024-09-09, 16:45:18, 21 procs): pss=5.8GB uss=5.0GB
ep 1 dev eval, step 3, min_wer -2.562, ce 0.868, fer 0.964, mem_usage:cuda:0 1.4GB
MEMORY: sub proc TDL worker 0(787160) increased RSS: rss=419.8MB pss=269.0MB uss=252.8MB shared=167.0MB
MEMORY: total (main 785298, 2024-09-09, 16:45:29, 21 procs): pss=5.8GB uss=5.0GB
ep 1 dev eval, step 4, min_wer -3.125, ce 0.857, fer 0.976, mem_usage:cuda:0 1.4GB
MEMORY: sub proc TDL worker 0(787160) increased RSS: rss=424.1MB pss=273.2MB uss=257.1MB shared=167.0MB
MEMORY: total (main 785298, 2024-09-09, 16:45:35, 21 procs): pss=5.8GB uss=5.0GB
ep 1 dev eval, step 5, min_wer -0.062, ce 0.703, fer 0.979, mem_usage:cuda:0 1.4GB
ep 1 dev eval, step 6, min_wer -0.562, ce 0.421, fer 0.976, mem_usage:cuda:0 1.5GB
ep 1 dev eval, step 7, min_wer -1.312, ce 0.796, fer 0.973, mem_usage:cuda:0 1.5GB
...
ep 1 dev eval, step 313, min_wer -1.672e-04, ce 0.731, fer 0.940, mem_usage:cuda:0 1.6GB
ep 1 dev eval, step 314, min_wer -0.195, ce 0.922, fer 0.946, mem_usage:cuda:0 1.6GB
ep 1 dev eval, step 315, min_wer 0.047, ce 0.380, fer 0.941, mem_usage:cuda:0 1.6GB
MEMORY: sub proc TDL worker 0(787160) increased RSS: rss=426.0MB pss=275.1MB uss=258.9MB shared=167.0MB
MEMORY: total (main 785298, 2024-09-09, 17:14:32, 21 procs): pss=5.8GB uss=5.0GB
ep 1 dev eval, step 316, min_wer -0.063, ce 0.511, fer 0.950, mem_usage:cuda:0 1.6GB
ep 1 dev eval, step 317, min_wer -0.180, ce 0.649, fer 0.949, mem_usage:cuda:0 1.6GB
Unhandled exception <class 'RuntimeError'> in thread <_MainThread(MainThread, started 140137470410752)>, proc 785299.

Thread <Thread(QueueFeederThread, started daemon 140128995497536)>:
Unhandled exception <class 'RuntimeError'> in thread <_MainThread(MainThread, started 139749057540096)>, proc 785301.

Thread <Thread(QueueFeederThread, started daemon 139740644894272)>:
Unhandled exception <class 'RuntimeError'> in thread <_MainThread(MainThread, started 140452254748672)>, proc 785300.
...
EXCEPTION
Traceback (most recent call last):
  File "/u/zeyer/setups/combined/2021-05-31/tools/returnn/rnn.py", line 11, in <module>
    line: main()
    locals:
      main = <local> <function main at 0x7f7421980ea0>
  File "/u/zeyer/setups/combined/2021-05-31/tools/returnn/returnn/__main__.py", line 737, in main
    line: execute_main_task()
    locals:
      execute_main_task = <global> <function execute_main_task at 0x7f7421980d60>
  File "/u/zeyer/setups/combined/2021-05-31/tools/returnn/returnn/__main__.py", line 543, in execute_main_task
    line: engine.train()
    locals:
      engine = <global> <returnn.torch.engine.Engine object at 0x7f732b9553d0>
      engine.train = <global> <bound method Engine.train of <returnn.torch.engine.Engine object at 0x7f732b9553d0>>
  File "/u/zeyer/setups/combined/2021-05-31/tools/returnn/returnn/torch/engine.py", line 226, in Engine.train
    line: self._check_missing_eval()
    locals:
      self = <local> <returnn.torch.engine.Engine object at 0x7f732b9553d0>
      self._check_missing_eval = <local> <bound method Engine._check_missing_eval of <returnn.torch.engine.Engine object at 0x7f732b9553d0>>
  File "/u/zeyer/setups/combined/2021-05-31/tools/returnn/returnn/torch/engine.py", line 1186, in Engine._check_missing_eval
    line: self.eval_model(skip_already_evaluated=True)
    locals:
      self = <local> <returnn.torch.engine.Engine object at 0x7f732b9553d0>
      self.eval_model = <local> <bound method Engine.eval_model of <returnn.torch.engine.Engine object at 0x7f732b9553d0>>
      skip_already_evaluated = <not found>
  File "/u/zeyer/setups/combined/2021-05-31/tools/returnn/returnn/torch/engine.py", line 523, in Engine.eval_model
    line: iter(data_loader)
    locals:
      iter = <builtin> <built-in function iter>
      data_loader = <local> <torch.utils.data.dataloader.DataLoader object at 0x7f7445ec5750>
  File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 433, in DataLoader.__iter__
    line: self._iterator = self._get_iterator()
    locals:
      self = <local> <torch.utils.data.dataloader.DataLoader object at 0x7f7445ec5750>
      self._iterator = <local> None
      self._get_iterator = <local> <bound method DataLoader._get_iterator of <torch.utils.data.dataloader.DataLoader object at 0x7f7445ec5750>>
  File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 386, in DataLoader._get_iterator
    line: return _MultiProcessingDataLoaderIter(self)
    locals:
      _MultiProcessingDataLoaderIter = <global> <class 'torch.utils.data.dataloader._MultiProcessingDataLoaderIter'>
      self = <local> <torch.utils.data.dataloader.DataLoader object at 0x7f7445ec5750>
  File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 991, in _MultiProcessingDataLoaderIter.__init__
    line: super().__init__(loader)
    locals:
      super = <builtin> <class 'super'>
      __init__ = <not found>
      loader = <local> <torch.utils.data.dataloader.DataLoader object at 0x7f7445ec5750>
  File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 570, in _BaseDataLoaderIter.__init__
    line: self._pg = dist.new_group(backend="gloo")
    locals:
      self = <local> <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7f72f2988fd0>
      self._pg = <local> None
      dist = <global> <module 'torch.distributed' from '/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/distributed/__init__.py'>
      dist.new_group = <global> <function new_group at 0x7f741e99b420>
      backend = <not found>
  File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 74, in _store_based_barrier
    line: func_return = func(*args, **kwargs)
    locals:
      func_return = <not found>
      func = <local> <function new_group at 0x7f741e99b380>
      args = <local> ()
      kwargs = <local> {'backend': 'gloo'}
  File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 3881, in new_group
    line: return _new_group_with_tag(ranks, timeout, backend, pg_options, None, use_local_synchronization=use_local_synchronization)
    locals:
      _new_group_with_tag = <global> <function _new_group_with_tag at 0x7f741e99b4c0>
      ranks = <local> None
      timeout = <local> datetime.timedelta(seconds=1800)
      backend = <local> 'gloo'
      pg_options = <local> None
      use_local_synchronization = <local> False
  File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 3944, in _new_group_with_tag
    line: pg, pg_store = _new_process_group_helper(
              group_world_size,
              group_rank,
              ranks,
              backend,
              default_store,
              group_name=group_name,
              pg_options=pg_options,
              timeout=timeout,
              pg_tag=pg_tag
          )
    locals:
      pg = <not found>
      pg_store = <not found>
      _new_process_group_helper = <global> <function _new_process_group_helper at 0x7f741e998540>
      group_world_size = <local> 4
      group_rank = <local> 1
      ranks = <local> [0, 1, 2, 3]
      backend = <local> 'gloo'
      default_store = <local> <torch.distributed.distributed_c10d.PrefixStore object at 0x7f74202eb730>
      group_name = <local> '2'
      pg_options = <local> None
      timeout = <local> datetime.timedelta(seconds=1800)
      pg_tag = <local> None
  File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 1264, in _new_process_group_helper
    line: backend_class = ProcessGroupGloo(backend_prefix_store, group_rank, group_size, timeout=timeout)
    locals:
      backend_class = <not found>
      ProcessGroupGloo = <global> <class 'torch.distributed.distributed_c10d.ProcessGroupGloo'>
      backend_prefix_store = <local> <torch.distributed.distributed_c10d.PrefixStore object at 0x7f72f2b983b0>
      group_rank = <local> 1
      group_size = <local> 4
      timeout = <local> datetime.timedelta(seconds=1800)
RuntimeError: Socket Timeout
Exception raised from doWait at ../torch/csrc/distributed/c10d/TCPStore.cpp:445 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f741fd92617 in /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/lib/libc10.s
o)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) + 0x68 (0x7f741fd4da56 in /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/sit
e-packages/torch/lib/libc10.so)
frame #2: c10d::TCPStore::doWait(c10::ArrayRef<std::string>, std::chrono::duration<long, std::ratio<1l, 1000l> >) + 0x32c (0x7f73ce9ec36c in /work/tools/users/zeyer/py-envs/py3.11-tor
ch2.1/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #3: c10d::TCPStore::doGet(std::string const&) + 0x32 (0x7f73ce9ed4f2 in /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #4: c10d::TCPStore::get(std::string const&) + 0x55 (0x7f73ce9ed915 in /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #5: c10d::PrefixStore::get(std::string const&) + 0x31 (0x7f73ce9a5161 in /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #6: c10d::PrefixStore::get(std::string const&) + 0x31 (0x7f73ce9a5161 in /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #7: c10d::PrefixStore::get(std::string const&) + 0x31 (0x7f73ce9a5161 in /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #8: c10d::PrefixStore::get(std::string const&) + 0x31 (0x7f73ce9a5161 in /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #9: <unknown function> + 0x55b7238 (0x7f73ce9d7238 in /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #10: gloo::rendezvous::PrefixStore::get(std::string const&) + 0x31 (0x7f73d04fd771 in /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/lib/libt
orch_cpu.so)
frame #11: gloo::rendezvous::Context::connectFullMesh(gloo::rendezvous::Store&, std::shared_ptr<gloo::transport::Device>&) + 0x287 (0x7f73d04fbbd7 in /work/tools/users/zeyer/py-envs/p
y3.11-torch2.1/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #12: c10d::ProcessGroupGloo::ProcessGroupGloo(c10::intrusive_ptr<c10d::Store, c10::detail::intrusive_target_default_null_type<c10d::Store> > const&, int, int, c10::intrusive_ptr
<c10d::ProcessGroupGloo::Options, c10::detail::intrusive_target_default_null_type<c10d::ProcessGroupGloo::Options> >) + 0x3a3 (0x7f73ce9c38d3 in /work/tools/users/zeyer/py-envs/py3.11
-torch2.1/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #13: <unknown function> + 0xbee32e (0x7f73e0f2232e in /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
frame #14: <unknown function> + 0xc0e593 (0x7f73e0f42593 in /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
frame #15: <unknown function> + 0x3f0ef4 (0x7f73e0724ef4 in /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #22: <unknown function> + 0x3ef789 (0x7f73e0723789 in /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
frame #51: <unknown function> + 0x291b7 (0x7f744c2761b7 in /work/tools/users/zeyer/linuxbrew/opt/glibc/lib/libc.so.6)
frame #52: __libc_start_main + 0x7c (0x7f744c27626c in /work/tools/users/zeyer/linuxbrew/opt/glibc/lib/libc.so.6)
frame #53: _start + 0x21 (0x401071 in /work/tools/users/zeyer/py-envs/py3.11-torch2.1/bin/python3.11)
...
```

**Comment by albertz** [comment]
I don't really know how sub process groups work. Or what a store is. Is `dist.new_group` creating a new sub group? Or is this independent? Is it using the existing store?

Note, we currently just do `dist.init_process_group(backend=None)`, which creates actually multiple process groups with multiple backends, one for each CPU and CUDA (and maybe potentially other devices). It uses the default backend for each, which is Gloo for CPU and NCCL for CUDA. I wonder if we maybe should do this more explicit (see https://github.com/rwth-i6/returnn/issues/1482#issuecomment-2352242496). I don't fully understand if this is actually one global process group which wraps the other process groups, or how this is really handled, and how this influences hte `dist.new_group` later.

However:

This `dist.new_group` will create another Gloo process group, for CPU tensors, as you see from the code and stacktrace.

I could imagine that maybe the calls `torch.distributed.all_reduce(_has_data, op=torch.distributed.ReduceOp.MIN)` trigger some synchronization which also influence this newly created Gloo process group.

**Comment by NeoLegends** [comment]
When it crashes "properly", w/o getting stuck in PG creation, the stack looks like this:

```EXCEPTION
Traceback (most recent call last):
  File "/home/mgunz/setups/2024-07-22--spanish-8khz-fh-v2/work/i6_core/tools/git/CloneGitRepositoryJob.WeRsHeLdDU7x/output/returnn/rnn.py", line 11, in <module>
    line: main()
    locals:
      main = <local> <function main at 0x7fd714598700>
  File "/nas/models/asr/mgunz/2024-07-22--spanish-8khz-fh-v2/i6_core/tools/git/CloneGitRepositoryJob.WeRsHeLdDU7x/output/returnn/returnn/__main__.py", line 737, in main
    line: execute_main_task()
    locals:
      execute_main_task = <global> <function execute_main_task at 0x7fd7145985e0>
  File "/nas/models/asr/mgunz/2024-07-22--spanish-8khz-fh-v2/i6_core/tools/git/CloneGitRepositoryJob.WeRsHeLdDU7x/output/returnn/returnn/__main__.py", line 543, in execute_main_task
    line: engine.train()
    locals:
      engine = <global> <returnn.torch.engine.Engine object at 0x7fd60173f9a0>
      engine.train = <global> <bound method Engine.train of <returnn.torch.engine.Engine object at 0x7fd60173f9a0>>
  File "/nas/models/asr/mgunz/2024-07-22--spanish-8khz-fh-v2/i6_core/tools/git/CloneGitRepositoryJob.WeRsHeLdDU7x/output/returnn/returnn/torch/engine.py", line 229, in Engine.train
    line: self._check_missing_eval()
    locals:
      self = <local> <returnn.torch.engine.Engine object at 0x7fd60173f9a0>
      self._check_missing_eval = <local> <bound method Engine._check_missing_eval of <returnn.torch.engine.Engine object at 0x7fd60173f9a0>>
  File "/nas/models/asr/mgunz/2024-07-22--spanish-8khz-fh-v2/i6_core/tools/git/CloneGitRepositoryJob.WeRsHeLdDU7x/output/returnn/returnn/torch/engine.py", line 1177, in Engine._check_missing_eval
    line: self.eval_model(skip_already_evaluated=True)
    locals:
      self = <local> <returnn.torch.engine.Engine object at 0x7fd60173f9a0>
      self.eval_model = <local> <bound method Engine.eval_model of <returnn.torch.engine.Engine object at 0x7fd60173f9a0>>
      skip_already_evaluated = <not found>
  File "/nas/models/asr/mgunz/2024-07-22--spanish-8khz-fh-v2/i6_core/tools/git/CloneGitRepositoryJob.WeRsHeLdDU7x/output/returnn/returnn/torch/engine.py", line 627, in Engine.eval_model
    line: torch.distributed.broadcast_object_list(ls, src=0, device=torch.device("cpu"))
    locals:
      torch = <global> <module 'torch' from '/usr/local/lib/python3.10/dist-packages/torch/__init__.py'>
      torch.distributed = <global> <module 'torch.distributed' from '/usr/local/lib/python3.10/dist-packages/torch/distributed/__init__.py'>
      torch.distributed.broadcast_object_list = <global> <function broadcast_object_list at 0x7fd62aae3f40>
      ls = <local> [EpochData(learningRate=0.0003134673366834171, error={
                   ':meta:cpu': 'Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz',
                   ':meta:device': 'NVIDIA RTX A5000',
                   ':meta:distributed': '<DistributedContext size=2 reduce_type=param>',
                   ':meta:effective_learning_rate': 0.0003134673366834171,
                   ':meta:epoch_num_train_...
      src = <not found>
      device = <not found>
      torch.device = <global> <class 'torch.device'>
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 75, in init_process_group
    line: return func(*args, **kwargs)
    locals:
      func = <local> <function broadcast_object_list at 0x7fd62aae3eb0>
      args = <local> ([EpochData(learningRate=0.0003134673366834171, error={
                     ':meta:cpu': 'Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz',
                     ':meta:device': 'NVIDIA RTX A5000',
                     ':meta:distributed': '<DistributedContext size=2 reduce_type=param>',
                     ':meta:effective_learning_rate': 0.0003134673366834171,
                     ':meta:epoch_num_train...
      kwargs = <local> {'src': 0, 'device': device(type='cpu')}
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 2649, in broadcast_object_list
    line: broadcast(object_sizes_tensor, src=src, group=group)
    locals:
      broadcast = <global> <function broadcast at 0x7fd62aae3760>
      object_sizes_tensor = <local> tensor([140557566291504])
      src = <local> 0
      group = <local> None
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 75, in init_process_group
    line: return func(*args, **kwargs)
    locals:
      func = <local> <function broadcast at 0x7fd62aae36d0>
      args = <local> (tensor([140557566291504]),)
      kwargs = <local> {'src': 0, 'group': None}
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 2144, in broadcast
    line: work.wait()
    locals:
      work = <local> <torch.distributed.distributed_c10d.Work object at 0x7fd620a73830>
      work.wait = <local> <bound method PyCapsule.wait of <torch.distributed.distributed_c10d.Work object at 0x7fd620a73830>>
RuntimeError: [/opt/apptek/pytorch-v2.3.0/third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:81] Timed out waiting 1800000ms for recv operation to complete```

**Comment by albertz** [comment]
Unfortunately, I still have the hang. Now it looks a bit different. During the hang, the stacktrace in rank 0:
```
    (Python) File "/u/zeyer/setups/combined/2021-05-31/tools/returnn/returnn/torch/engine.py", line 226, in train
        self._check_missing_eval()
      Arguments:
        self: <Engine at 0x7edc82ac2c10>
    (Python) File "/u/zeyer/setups/combined/2021-05-31/tools/returnn/returnn/torch/engine.py", line 1208, in _check_missing_eval
        self.eval_model(skip_already_evaluated=True)
      Arguments:
        self: <Engine at 0x7edc82ac2c10>
      Locals:
        name: "dev"
    (Python) File "/u/zeyer/setups/combined/2021-05-31/tools/returnn/returnn/torch/engine.py", line 542, in eval_model
        torch.distributed.broadcast(_has_data, src=0)
      Arguments:
        self: <cell at 0x7edc807e1b40>
      Locals:
        accumulated_losses_dict: <cell at 0x7edc829590c0>
        eval_dump_str: [], len 0
        accumulated_inv_norm_factors_dict: <NumbersDict at 0x7edc80465290>
        skip_already_evaluated: True
        score_keys: <set at 0x7edc4007dc40>
        inv_norm_factors_dict: <NumbersDict at 0x7edb92c1cf10>
        extern_data: <TensorDict at 0x7edc801d4250>
        eval_info: <NumbersDict at 0x7edb92bdb590>
        dataset: <MultiProcDataset at 0x7edc828f51d0>
        train_ctx: <RunCtx at 0x7edc403cf910>
        data_loader: <DataLoader at 0x7edd770d7050>
        _has_data: <Tensor at 0x7edc407a0ad0>
        step_idx: 100
        error_keys: <set at 0x7edc4007db60>
        losses_dict: <NumbersDict at 0x7edc40129290>
        dataset_name: <cell at 0x7edd76f878b0>
        extern_data_raw: {"classes": <Tensor at 0x7edc407a26f0>, "classes:seq_len": <Tensor at 0x7edc407a32f0>, ...}
    (Python) File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
        return func(*args, **kwargs)
      Locals:
        func: <cell at 0x7edd4e3b4130>
        kwargs: {"src": 0}
        args: (<Tensor at 0x7edc407a0ad0>), len 1
    (Python) File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 1906, in broadcast
        work = default_pg.broadcast([tensor], opts)
      Arguments:
        group: None
        async_op: False
        src: 0
        tensor: <Tensor at 0x7edc407a0ad0>
      Locals:
        default_pg: <torch._C._distributed_c10d.ProcessGroup at 0x7edca36c6170>
        opts: <torch._C._distributed_c10d.BroadcastOptions at 0x7edb92d39f30>
```

And then in some other rank (here rank 1):
```
    (Python) File "/u/zeyer/setups/combined/2021-05-31/tools/returnn/returnn/torch/engine.py", line 226, in train
        self._check_missing_eval()
      Arguments:
        self: <Engine at 0x7b05143e09d0>
    (Python) File "/u/zeyer/setups/combined/2021-05-31/tools/returnn/returnn/torch/engine.py", line 1208, in _check_missing_eval
        self.eval_model(skip_already_evaluated=True)
      Arguments:
        self: <Engine at 0x7b05143e09d0>
      Locals:
        name: "dev"
    (Python) File "/u/zeyer/setups/combined/2021-05-31/tools/returnn/returnn/torch/engine.py", line 523, in eval_model
        iter(data_loader)
      Arguments:
        self: <cell at 0x7b0513755420>
      Locals:
        dataset_name: <cell at 0x7b05ff9ef910>
        accumulated_losses_dict: <cell at 0x7b05139c3f40>
        _has_data: None
        data_loader: <DataLoader at 0x7b05ffb2f8d0>
        dataset: <MultiProcDataset at 0x7b051374e710>
        error_keys: None
        score_keys: None
        eval_dump_str: [], len 0
        skip_already_evaluated: True
    (Python) File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 433, in __iter__
        self._iterator = self._get_iterator()
      Arguments:
        self: <DataLoader at 0x7b05ffb2f8d0>
    (Python) File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 386, in _get_iterator
        return _MultiProcessingDataLoaderIter(self)
      Arguments:
        self: <DataLoader at 0x7b05ffb2f8d0>
    (Python) File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 991, in __init__
        super().__init__(loader)
      Arguments:
        loader: <DataLoader at 0x7b05ffb2f8d0>
        self: <_MultiProcessingDataLoaderIter at 0x7b0510cb8b10>
      Locals:
        __class__: <cell at 0x7b0534fbf430>
    (Python) File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 570, in __init__
        self._pg = dist.new_group(backend="gloo")
      Arguments:
        loader: <DataLoader at 0x7b05ffb2f8d0>
        self: <_MultiProcessingDataLoaderIter at 0x7b0510cb8b10>
    (Python) File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 74, in wrapper
        func_return = func(*args, **kwargs)
      Locals:
        func: <cell at 0x7b05cb1a09d0>
        t1: 1726746574674175359
        kwargs: {"backend": "gloo"}
        args: (), len 0
    (Python) File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 3881, in new_group
        return _new_group_with_tag(ranks, timeout, backend, pg_options, None, use_local_synchronization=use_local_synchronization)
      Arguments:
        use_local_synchronization: False
        pg_options: None
        backend: "gloo"
        timeout: <datetime.timedelta at 0x7b05cb164900>
        ranks: None
    (Python) File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 3944, in _new_group_with_tag
        pg, pg_store = _new_process_group_helper(
      Arguments:
        use_local_synchronization: False
        pg_options: None
        backend: "gloo"
        timeout: <datetime.timedelta at 0x7b05cb164900>
        pg_tag: None
        ranks: [0, 1, 2, 3], len 4
      Locals:
        group_name: "2"
        group_rank: 1
        group_world_size: 4
        global_world_size: 4
        global_rank: 1
        default_store: <torch._C._distributed_c10d.PrefixStore at 0x7b05d8121170>
        default_backend: "undefined"
        default_pg: <torch._C._distributed_c10d.ProcessGroup at 0x7b052d095370>
    (Python) File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 1264, in _new_process_group_helper
        backend_class = ProcessGroupGloo(backend_prefix_store, group_rank, group_size, timeout=timeout)
      Arguments:
        pg_tag: None
        timeout: <datetime.timedelta at 0x7b05cb164900>
        group_name: "2"
        store: <torch._C._distributed_c10d.PrefixStore at 0x7b05d8121170>
        backend: "gloo"
        pg_options: None
        global_ranks_in_group: [0, 1, 2, 3], len 4
        group_rank: 1
        group_size: 4
      Locals:
        backend_prefix_store: <torch._C._distributed_c10d.PrefixStore at 0x7b05101c24b0>
        backend_str: "gloo"
        backend_config: <BackendConfig at 0x7b05101c2490>
        pg: <torch._C._distributed_c10d.ProcessGroup at 0x7b05101c24f0>
        device: "cpu"
        base_pg_options: <torch._C._distributed_c10d.Options at 0x7b05101c2570>
        global_rank: 1
        is_default_group: False
        prefix_store: <torch._C._distributed_c10d.PrefixStore at 0x7b05101c2530>
```

And then the timeout happens:
```
...
ep 1 dev eval, step 97, min_wer -0.688, ce 0.859, fer 0.977, mem_usage:cuda:0 1.6GB
ep 1 dev eval, step 98, min_wer -0.187, ce 0.469, fer 0.964, mem_usage:cuda:0 1.6GB
ep 1 dev eval, step 99, min_wer 0.083, ce 0.286, fer 0.969, mem_usage:cuda:0 1.6GB
[I ProcessGroupWrapper.cpp:562] [Rank 0] Running collective: CollectiveFingerPrint(SequenceNumber=1, OpType=BROADCAST, TensorShape=[1], TensorDtypes=Char, TensorDeviceTypes=TensorOptions(dtype=float (default), device=cpu, layout=Strided (default), requires_grad=false (default), pinned_memory=false (default), memory_format=(nullopt)))
Unhandled exception <class 'RuntimeError'> in thread <_MainThread(MainThread, started 129187316453376)>, proc 25928.
Unhandled exception <class 'RuntimeError'> in thread <_MainThread(MainThread, started 123955313799168)>, proc 25927.


Thread <Thread(QueueFeederThread, started daemon 129181828503104)>:
Thread <Thread(QueueFeederThread, started daemon 123950088574528)>:
Unhandled exception <class 'RuntimeError'> in thread <_MainThread(MainThread, started 135265771380736)>, proc 25926.

...

RuntimeError: Socket Timeout
Exception raised from doWait at ../torch/csrc/distributed/c10d/TCPStore.cpp:445 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x757e97d92617 in /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) + 0x68 (0x757e97d4da56 in /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/l
ib/libc10.so)
frame #2: c10d::TCPStore::doWait(c10::ArrayRef<std::string>, std::chrono::duration<long, std::ratio<1l, 1000l> >) + 0x32c (0x757e468d536c in /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.
11/site-packages/torch/lib/libtorch_cpu.so)
frame #3: c10d::TCPStore::doGet(std::string const&) + 0x32 (0x757e468d64f2 in /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #4: c10d::TCPStore::get(std::string const&) + 0x55 (0x757e468d6915 in /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #5: c10d::PrefixStore::get(std::string const&) + 0x31 (0x757e4688e161 in /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #6: c10d::PrefixStore::get(std::string const&) + 0x31 (0x757e4688e161 in /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #7: c10d::PrefixStore::get(std::string const&) + 0x31 (0x757e4688e161 in /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #8: c10d::PrefixStore::get(std::string const&) + 0x31 (0x757e4688e161 in /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #9: <unknown function> + 0x55b7238 (0x757e468c0238 in /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #10: gloo::rendezvous::PrefixStore::get(std::string const&) + 0x31 (0x757e483e6771 in /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #11: gloo::rendezvous::Context::connectFullMesh(gloo::rendezvous::Store&, std::shared_ptr<gloo::transport::Device>&) + 0x287 (0x757e483e4bd7 in /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib
/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #12: c10d::ProcessGroupGloo::ProcessGroupGloo(c10::intrusive_ptr<c10d::Store, c10::detail::intrusive_target_default_null_type<c10d::Store> > const&, int, int, c10::intrusive_ptr<c10d::ProcessGrou
pGloo::Options, c10::detail::intrusive_target_default_null_type<c10d::ProcessGroupGloo::Options> >) + 0x3a3 (0x757e468ac8d3 in /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packag
es/torch/lib/libtorch_cpu.so)
frame #13: <unknown function> + 0xbee32e (0x757e58e0b32e in /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
frame #14: <unknown function> + 0xc0e593 (0x757e58e2b593 in /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
frame #15: <unknown function> + 0x3f0ef4 (0x757e5860def4 in /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #22: <unknown function> + 0x3ef789 (0x757e5860c789 in /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
frame #51: <unknown function> + 0x291b7 (0x757ec41df1b7 in /work/tools/users/zeyer/linuxbrew/opt/glibc/lib/libc.so.6)
frame #52: __libc_start_main + 0x7c (0x757ec41df26c in /work/tools/users/zeyer/linuxbrew/opt/glibc/lib/libc.so.6)
frame #53: _start + 0x21 (0x401071 in /work/tools/users/zeyer/py-envs/py3.11-torch2.1/bin/python3.11)
```

So, as you see, now rank 0 hangs as well because it tries to sync with the other ranks, but it can't because the other ranks hang already. And the hang is not resolved by the additional `_has_data` sync, as I hoped it would do.

So, I still don't understand why this problem does not occur when the eval is faster.

Just to be sure, I also tested your suggested variant to have this common for all ranks:
```python
            data_loader = self._eval_dataloaders[dataset_name]

            # We need to make sure the data loader iterator was created for proper synchronization.
            # However, we only want to do evaluation on rank 0 for simplicity.
            data_loader = iter(data_loader)
```
However, that doesn't make any difference. Rank 0 proceeds here while the other ranks hang when creating the `iter`. So this is really not the issue.

**Comment by albertz** [comment]
Oh, even worse: Now with the fix (PR #1627), even my usual experiments also hang! To double check that this is caused by PR #1627, I reverted it, and then it does not hang anymore... I don't really understand... But for now, I think I will push the revert to master, as all my experiments are always hanging now...

**Comment by albertz** [comment]
Note, the original reported problem is also solved now by the fix. Although I still don't fully understand how the sync of the default CPU Gloo process group (PG) influences the newly created Gloo PG. It might also be environment dependent, or PyTorch version dependent. @NeoLegends was not able to reproduce the exact same error (with PyTorch 2.2). But anyway, it works now.

**Comment by albertz** [comment]
Also note, currently we do the sync every `step_idx % 100 == 0`. This is somewhat arbitrary. It's probably fine for most cases (also my current case), but it would fail if the first 100 steps take even longer than 30 mins. An alternative would be to do this time-based, i.e. check sth like `time.time() - last_sync_time >= 60` or so, i.e. automatically sync every minute once.
